-- Reference taxonomy: official SAT domains and skills. Re-runnable.
insert into public.domains (id, section, name, weight_pct, sort_order) values ('craft_structure', 'rw', 'Craft and Structure', 28, 1) on conflict (id) do nothing;
insert into public.domains (id, section, name, weight_pct, sort_order) values ('information_ideas', 'rw', 'Information and Ideas', 26, 2) on conflict (id) do nothing;
insert into public.domains (id, section, name, weight_pct, sort_order) values ('standard_conventions', 'rw', 'Standard English Conventions', 26, 3) on conflict (id) do nothing;
insert into public.domains (id, section, name, weight_pct, sort_order) values ('expression_ideas', 'rw', 'Expression of Ideas', 20, 4) on conflict (id) do nothing;
insert into public.domains (id, section, name, weight_pct, sort_order) values ('algebra', 'math', 'Algebra', 35, 5) on conflict (id) do nothing;
insert into public.domains (id, section, name, weight_pct, sort_order) values ('advanced_math', 'math', 'Advanced Math', 35, 6) on conflict (id) do nothing;
insert into public.domains (id, section, name, weight_pct, sort_order) values ('psda', 'math', 'Problem-Solving and Data Analysis', 15, 7) on conflict (id) do nothing;
insert into public.domains (id, section, name, weight_pct, sort_order) values ('geometry_trig', 'math', 'Geometry and Trigonometry', 15, 8) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('words_in_context', 'craft_structure', 'Words in Context', 1) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('text_structure_purpose', 'craft_structure', 'Text Structure and Purpose', 2) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('cross_text_connections', 'craft_structure', 'Cross-Text Connections', 3) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('central_ideas_details', 'information_ideas', 'Central Ideas and Details', 4) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('evidence_textual', 'information_ideas', 'Command of Evidence (Textual)', 5) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('evidence_quantitative', 'information_ideas', 'Command of Evidence (Quantitative)', 6) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('inferences', 'information_ideas', 'Inferences', 7) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('boundaries', 'standard_conventions', 'Boundaries', 8) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('form_structure_sense', 'standard_conventions', 'Form, Structure, and Sense', 9) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('rhetorical_synthesis', 'expression_ideas', 'Rhetorical Synthesis', 10) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('transitions', 'expression_ideas', 'Transitions', 11) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('linear_eq_one_var', 'algebra', 'Linear equations in one variable', 12) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('linear_eq_two_var', 'algebra', 'Linear equations in two variables', 13) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('linear_functions', 'algebra', 'Linear functions', 14) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('systems_two_linear', 'algebra', 'Systems of two linear equations', 15) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('linear_inequalities', 'algebra', 'Linear inequalities', 16) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('equivalent_expressions', 'advanced_math', 'Equivalent expressions', 17) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('nonlinear_eq_systems', 'advanced_math', 'Nonlinear equations and systems', 18) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('nonlinear_functions', 'advanced_math', 'Nonlinear functions', 19) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('ratios_rates_proportions', 'psda', 'Ratios, rates and proportions', 20) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('percentages', 'psda', 'Percentages', 21) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('one_var_data', 'psda', 'One-variable data', 22) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('two_var_data', 'psda', 'Two-variable data', 23) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('probability', 'psda', 'Probability', 24) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('sample_stats_moe', 'psda', 'Sample statistics and margin of error', 25) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('evaluating_claims', 'psda', 'Evaluating statistical claims', 26) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('area_volume', 'geometry_trig', 'Area and volume', 27) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('lines_angles_triangles', 'geometry_trig', 'Lines, angles and triangles', 28) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('right_triangles_trig', 'geometry_trig', 'Right triangles and trigonometry', 29) on conflict (id) do nothing;
insert into public.skills (id, domain_id, name, sort_order) values ('circles', 'geometry_trig', 'Circles', 30) on conflict (id) do nothing;
