insert into public.tests (id, slug, title, subtitle, test_type, section_scope, focus_domain_id, difficulty, description, sort_order) values ('61816ca3-3ec1-5252-a036-dc61865fd670', 'drill-rw-expression', 'Writing: Expression of Ideas', 'Transitions and rhetorical synthesis', 'drill', 'rw', 'expression_ideas', 'mixed', 'Choosing logical transitions and selecting the notes that best accomplish a stated rhetorical goal.', 13) on conflict (slug) do nothing;
insert into public.test_parts (id, test_id, part_index, title, section, duration_seconds) values ('cc045c10-36c8-5d41-a95d-a6d8ea47b301', '61816ca3-3ec1-5252-a036-dc61865fd670', 1, 'Writing: Expression of Ideas', 'rw', 600) on conflict (test_id, part_index) do nothing;
insert into public.questions (id, part_id, order_index, domain_id, skill_id, difficulty, question_type, passage, prompt, choices, correct_answer, accepted_answers, explanation) values ('c0aba868-56b3-5c73-a5e6-e18c397dd7cc', 'cc045c10-36c8-5d41-a95d-a6d8ea47b301', 1, 'expression_ideas', 'transitions', 'easy', 'mc', 'Bamboo can grow nearly a metre in a single day. _______ it is increasingly used as a construction material where fast-growing timber is scarce.', 'Which choice completes the text with the most logical transition?', '[{"key":"A","text":"However,"},{"key":"B","text":"For this reason,"},{"key":"C","text":"In contrast,"},{"key":"D","text":"Admittedly,"}]'::jsonb, 'B', null, 'The second sentence states a consequence of the growth rate described in the first, so a causal transition is needed. ''However'' would falsely mark the sentences as opposed.') on conflict (id) do nothing;
insert into public.questions (id, part_id, order_index, domain_id, skill_id, difficulty, question_type, passage, prompt, choices, correct_answer, accepted_answers, explanation) values ('1468795c-56a4-5914-a18d-1f08d4c5584f', 'cc045c10-36c8-5d41-a95d-a6d8ea47b301', 2, 'expression_ideas', 'transitions', 'easy', 'mc', 'The 1970 expedition returned with hundreds of soil samples. _______ almost none were catalogued, and most were discarded within a decade.', 'Which choice completes the text with the most logical transition?', '[{"key":"A","text":"Accordingly,"},{"key":"B","text":"Yet"},{"key":"C","text":"Likewise,"},{"key":"D","text":"In summary,"}]'::jsonb, 'B', null, 'Collecting hundreds of samples and then discarding them is a contrast, which ''Yet'' marks. ''Accordingly'' would present the loss as the natural result of collecting, which makes no sense.') on conflict (id) do nothing;
insert into public.questions (id, part_id, order_index, domain_id, skill_id, difficulty, question_type, passage, prompt, choices, correct_answer, accepted_answers, explanation) values ('f9034177-fc87-517d-ae25-e7f63a8bb4d2', 'cc045c10-36c8-5d41-a95d-a6d8ea47b301', 3, 'expression_ideas', 'rhetorical_synthesis', 'medium', 'mc', 'While researching, a student took these notes:
• Kente cloth is woven in narrow strips on a horizontal loom.
• Strips are cut and sewn edge to edge to make a full cloth.
• Patterns carry names and meanings.
• The technique allows a large cloth to be made on a small loom.

The student wants to explain the practical advantage of the strip-weaving method.', 'Which choice most effectively uses relevant information from the notes to accomplish this goal?', '[{"key":"A","text":"Kente patterns carry names and meanings recognised by weavers and wearers."},{"key":"B","text":"Because kente is woven in narrow strips that are later sewn together, a large cloth can be produced on a small loom."},{"key":"C","text":"Kente cloth is woven on a horizontal loom in narrow strips."},{"key":"D","text":"Kente strips are cut and sewn edge to edge."}]'::jsonb, 'B', null, 'The question asks for the practical advantage, so the answer must connect the strip method to the outcome it makes possible. Choices C and D describe the method without naming any benefit.') on conflict (id) do nothing;
insert into public.questions (id, part_id, order_index, domain_id, skill_id, difficulty, question_type, passage, prompt, choices, correct_answer, accepted_answers, explanation) values ('53c435a4-2d4f-5d0f-af1f-a83db563175a', 'cc045c10-36c8-5d41-a95d-a6d8ea47b301', 4, 'expression_ideas', 'transitions', 'medium', 'mc', 'Lead pipes were installed in millions of homes because lead is soft and easy to bend. _______ that same softness means the metal dissolves readily into water that sits in the pipe.', 'Which choice completes the text with the most logical transition?', '[{"key":"A","text":"Unfortunately,"},{"key":"B","text":"Therefore,"},{"key":"C","text":"For example,"},{"key":"D","text":"Similarly,"}]'::jsonb, 'A', null, 'The property that made lead attractive is now presented as a hazard, so a contrastive-evaluative transition fits. ''Therefore'' would suggest the dissolving is a benefit following from ease of installation.') on conflict (id) do nothing;
insert into public.questions (id, part_id, order_index, domain_id, skill_id, difficulty, question_type, passage, prompt, choices, correct_answer, accepted_answers, explanation) values ('2bc87c3e-0b58-5eaa-acd5-c8d748b8b7aa', 'cc045c10-36c8-5d41-a95d-a6d8ea47b301', 5, 'expression_ideas', 'rhetorical_synthesis', 'medium', 'mc', 'While researching, a student took these notes:
• The Aral Sea was the fourth largest lake in the world in 1960.
• Rivers feeding it were diverted for cotton irrigation.
• By 2010 it had lost about 90 percent of its volume.
• A dam completed in 2005 has partly restored the northern portion.

The student wants to emphasise the scale of the loss.', 'Which choice most effectively uses relevant information from the notes to accomplish this goal?', '[{"key":"A","text":"Once the world''s fourth largest lake, the Aral Sea had lost roughly 90 percent of its volume by 2010."},{"key":"B","text":"A dam completed in 2005 has partly restored the northern Aral Sea."},{"key":"C","text":"Rivers feeding the Aral Sea were diverted to irrigate cotton."},{"key":"D","text":"The Aral Sea has changed considerably since 1960."}]'::jsonb, 'A', null, 'Scale needs both the former standing and the measured proportion lost, which only choice A supplies. Choice D gestures at change without any figure to convey magnitude.') on conflict (id) do nothing;
insert into public.questions (id, part_id, order_index, domain_id, skill_id, difficulty, question_type, passage, prompt, choices, correct_answer, accepted_answers, explanation) values ('65edc486-0b25-528e-a438-b1235f0790b8', 'cc045c10-36c8-5d41-a95d-a6d8ea47b301', 6, 'expression_ideas', 'transitions', 'hard', 'mc', 'Most accounts credit the 1928 discovery of penicillin with the arrival of antibiotics. The mould''s effect had, however, been noticed and published by other researchers decades earlier. _______ what distinguished 1928 was not the observation but the decade of work that turned it into a usable drug.', 'Which choice completes the text with the most logical transition?', '[{"key":"A","text":"Consequently,"},{"key":"B","text":"In short,"},{"key":"C","text":"By contrast,"},{"key":"D","text":"Instead,"}]'::jsonb, 'B', null, 'The final sentence condenses the preceding correction into a summary judgement, which is what ''In short'' signals. ''Consequently'' would claim the summary is caused by the earlier publications rather than drawn from them.') on conflict (id) do nothing;
insert into public.questions (id, part_id, order_index, domain_id, skill_id, difficulty, question_type, passage, prompt, choices, correct_answer, accepted_answers, explanation) values ('904eade7-aa8e-59fc-a544-9ddd6610ac31', 'cc045c10-36c8-5d41-a95d-a6d8ea47b301', 7, 'expression_ideas', 'rhetorical_synthesis', 'hard', 'mc', 'While researching, a student took these notes:
• Coral reefs cover less than 0.1 percent of the ocean floor.
• About 25 percent of marine species depend on them at some stage of life.
• Reef fish supply protein to hundreds of millions of coastal people.
• Bleaching events have become five times more frequent since 1980.

The student wants to argue that reef loss is a problem out of proportion to the area involved.', 'Which choice most effectively uses relevant information from the notes to accomplish this goal?', '[{"key":"A","text":"Bleaching events have become five times more frequent since 1980."},{"key":"B","text":"Coral reefs cover less than 0.1 percent of the ocean floor yet about a quarter of marine species depend on them."},{"key":"C","text":"Reef fish supply protein to hundreds of millions of coastal people."},{"key":"D","text":"Coral reefs are found in shallow tropical waters around the world."}]'::jsonb, 'B', null, 'The argument turns on a mismatch between tiny area and large dependence, and only choice B places both figures side by side. Choice C shows importance but gives no measure of area to contrast it with.') on conflict (id) do nothing;
insert into public.questions (id, part_id, order_index, domain_id, skill_id, difficulty, question_type, passage, prompt, choices, correct_answer, accepted_answers, explanation) values ('48d08369-5eee-5e5f-a6f1-0263793e4322', 'cc045c10-36c8-5d41-a95d-a6d8ea47b301', 8, 'expression_ideas', 'transitions', 'hard', 'mc', 'Adding a lane to a congested motorway usually reduces travel time at first. Within a few years, however, traffic volumes rise until delays return to roughly their previous level. _______ the capacity was not absorbed by existing drivers but by trips that were not previously made.', 'Which choice completes the text with the most logical transition?', '[{"key":"A","text":"Even so,"},{"key":"B","text":"That is,"},{"key":"C","text":"Nevertheless,"},{"key":"D","text":"Otherwise,"}]'::jsonb, 'B', null, 'The final sentence explains the mechanism behind the rebound just described, so a clarifying restatement connector is required. ''Even so'' and ''Nevertheless'' would wrongly frame the explanation as an objection to the data it explains.') on conflict (id) do nothing;
