// Full Mock 2 — Math, Modules 1 and 2. 22 questions per module.
//
// Difficulty is deliberately raised over Mock 1, which tested too easy. It is
// calibrated against the hard end of College Board's official Practice Test 4:
// complementary-angle trigonometry, exponential models needing a rate-period
// conversion, counting solutions of linear systems, invariance of statistics
// under transformation, circle equations requiring completing the square, and
// composite solids.
//
// Module 2 is written as the UPPER adaptive module — the harder second module a
// student scoring in the 1300s would actually be routed into.
//
// Domain mix follows official weightings: Algebra 8, Advanced Math 8,
// Problem-Solving and Data Analysis 3, Geometry and Trigonometry 3 per module.
// All questions are original and do not reproduce College Board items.

export const MOCK2_MATH_1 = [
  // ---- Algebra (8) ----
  {
    d: "algebra",
    s: "linear_eq_one_var",
    diff: "easy",
    type: "mc",
    prompt: "If 7(x − 3) = 2x + 4, what is the value of x?",
    choices: ["3", "5", "7", "25"],
    ans: "B",
    exp: "Distributing gives 7x − 21 = 2x + 4, so 5x = 25 and x = 5. Choice D is the value of 5x, which is the most common place to stop early.",
  },
  {
    d: "algebra",
    s: "linear_functions",
    diff: "medium",
    type: "spr",
    prompt: "A line passes through the points (2, 7) and (6, 19). What is the y-coordinate of the point where this line crosses the y-axis?",
    ans: "1",
    alt: ["1.0"],
    exp: "The slope is (19 − 7)/(6 − 2) = 12/4 = 3. Substituting (2, 7) into y = 3x + b gives 7 = 6 + b, so b = 1. Answering 7 mistakes the given point for the intercept.",
  },
  {
    d: "algebra",
    s: "linear_eq_two_var",
    diff: "medium",
    type: "mc",
    prompt: "Line ℓ has equation 2x + 5y = 20. Line m is perpendicular to ℓ and passes through the point (4, 1). What is the y-intercept of line m?",
    choices: ["−9", "−1", "1", "9"],
    ans: "A",
    exp: "Line ℓ has slope −2/5, so a perpendicular line has slope 5/2. Using y − 1 = (5/2)(x − 4) gives y = (5/2)x − 9, so the y-intercept is −9. Choice D drops the sign produced by −(5/2)(4) + 1.",
  },
  {
    d: "algebra",
    s: "systems_two_linear",
    diff: "medium",
    type: "mc",
    prompt: "If 3x + 2y = 16 and 5x − 2y = 8, what is the value of x + y?",
    choices: ["3", "3.5", "6.5", "10"],
    ans: "C",
    exp: "Adding the equations eliminates y: 8x = 24, so x = 3. Then 9 + 2y = 16 gives y = 3.5, and x + y = 6.5. Choices A and B are the individual values — the question asks for their sum, which is exactly the trap.",
  },
  {
    d: "algebra",
    s: "linear_inequalities",
    diff: "medium",
    type: "mc",
    prompt: "A caterer charges a fixed setup fee of 120 birr plus 45 birr for each guest. If the total cost must not exceed 2,900 birr, what is the greatest number of guests that can be served?",
    choices: ["60", "61", "62", "66"],
    ans: "B",
    exp: "The amount available for guests is 2,900 − 120 = 2,780 birr, and 2,780 ÷ 45 ≈ 61.8, so only 61 whole guests fit. Choice C rounds up, which would push the total over the limit.",
  },
  {
    d: "algebra",
    s: "systems_two_linear",
    diff: "hard",
    type: "mc",
    prompt: "kx + 3y = 12 and 4x + 6y = 30. For what value of k does this system of equations have no solution?",
    choices: ["1", "2", "4", "8"],
    ans: "B",
    exp: "A system has no solution when the lines are parallel but distinct, so the coefficients must be proportional while the constants are not: k/4 = 3/6 gives k = 2. Checking, 12/30 ≠ 1/2, so the lines really are distinct rather than identical.",
  },
  {
    d: "algebra",
    s: "linear_eq_two_var",
    diff: "hard",
    type: "mc",
    prompt: "The graph of 3x + ky = 12 in the xy-plane passes through the points (2, 3) and (6, −3). What is the value of k?",
    choices: ["1", "2", "3", "6"],
    ans: "B",
    exp: "Substituting (2, 3) gives 6 + 3k = 12, so k = 2. Verifying with the second point: 3(6) + 2(−3) = 18 − 6 = 12, which confirms it. Using only one point without checking is what makes the other values look plausible.",
  },
  {
    d: "algebra",
    s: "linear_functions",
    diff: "hard",
    type: "spr",
    prompt: "The function f is linear, with f(3) = 11 and f(7) = 3. For what value of x does f(x) = 0?",
    ans: "8.5",
    alt: ["17/2", "8.50"],
    exp: "The slope is (3 − 11)/(7 − 3) = −2, so f(x) = 11 − 2(x − 3) = 17 − 2x. Setting 17 − 2x = 0 gives x = 8.5. Answering 17 solves for the y-intercept instead of the x-intercept.",
  },

  // ---- Advanced Math (8) ----
  {
    d: "advanced_math",
    s: "equivalent_expressions",
    diff: "easy",
    type: "mc",
    prompt: "Which expression is equivalent to (2x³)(5x⁴)?",
    choices: ["10x⁷", "10x¹²", "7x⁷", "7x¹²"],
    ans: "A",
    exp: "Multiply the coefficients and add the exponents: 2 × 5 = 10 and x³ · x⁴ = x⁷. Choice B multiplies the exponents instead of adding them, and choices C and D add the coefficients.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_functions",
    diff: "medium",
    type: "mc",
    prompt: "The function f is defined by f(x) = x² − 6x + 5. What is the minimum value of f(x)?",
    choices: ["−4", "−3", "3", "5"],
    ans: "A",
    exp: "The vertex lies at x = −b/(2a) = 6/2 = 3, and f(3) = 9 − 18 + 5 = −4. Choice C is the x-coordinate of the vertex rather than the minimum value, which is the y-coordinate.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_eq_systems",
    diff: "medium",
    type: "spr",
    prompt: "What is the positive solution to the equation x² = 4x + 21?",
    ans: "7",
    alt: ["7.0"],
    exp: "Rearranging gives x² − 4x − 21 = 0, which factors as (x − 7)(x + 3) = 0, so x = 7 or x = −3. The question asks only for the positive solution, so 7 is the answer.",
  },
  {
    d: "advanced_math",
    s: "equivalent_expressions",
    diff: "medium",
    type: "mc",
    prompt: "For x ≠ 3 and x ≠ −3, which expression is equivalent to (x + 3)/(x² − 9)?",
    choices: ["1/(x − 3)", "1/(x + 3)", "x − 3", "1/9"],
    ans: "A",
    exp: "The denominator factors as (x + 3)(x − 3), so the (x + 3) cancels and leaves 1/(x − 3). Choice B cancels the wrong factor, which is the natural slip when the numerator is matched to the first factor written.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_functions",
    diff: "hard",
    type: "mc",
    prompt: "The function g is defined by g(x) = 2(x − 4)² − 18. The graph of y = g(x) crosses the x-axis at x = a and x = b, where a < b. What is the value of b − a?",
    choices: ["3", "6", "9", "18"],
    ans: "B",
    exp: "Setting 2(x − 4)² − 18 = 0 gives (x − 4)² = 9, so x − 4 = ±3 and the zeros are 1 and 7. Their difference is 6. Choice A gives only the distance from the vertex to one zero.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_eq_systems",
    diff: "hard",
    type: "mc",
    prompt: "The system of equations y = x² − 2x + 5 and y = k has exactly one solution. What is the value of k?",
    choices: ["0", "4", "5", "6"],
    ans: "B",
    exp: "A horizontal line meets a parabola exactly once only at the vertex. The vertex is at x = 1, where y = 1 − 2 + 5 = 4, so k = 4. Choice C is the y-intercept, which the line would cross twice.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_eq_systems",
    diff: "hard",
    type: "spr",
    prompt: "What is the solution to the equation √(2x + 7) = x − 4?",
    ans: "9",
    alt: ["9.0"],
    exp: "Squaring gives 2x + 7 = x² − 8x + 16, so x² − 10x + 9 = 0 and (x − 1)(x − 9) = 0, giving x = 1 or x = 9. Checking both matters: x = 1 gives √9 = 3 but 1 − 4 = −3, so it is extraneous; only x = 9 works, since √25 = 5 = 9 − 4.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_functions",
    diff: "hard",
    type: "mc",
    prompt: "The value of a machine, in dollars, is modeled by V(t) = 5,000(0.36)^(t/24), where t is the number of months since it was purchased. By what percent does the value of the machine decrease each year?",
    choices: ["18%", "36%", "40%", "60%"],
    ans: "C",
    exp: "One year is 12 months, so the yearly factor is 0.36^(12/24) = 0.36^(1/2) = 0.6, meaning 60% of the value remains and 40% is lost. Choice D reports the fraction remaining rather than the decrease, and choice B uses the two-year factor without converting.",
  },

  // ---- Problem-Solving and Data Analysis (3) ----
  {
    d: "psda",
    s: "percentages",
    diff: "medium",
    type: "mc",
    prompt: "A jacket is marked down by 30%. During a later sale, that reduced price is marked down by a further 20%. The final price is what percent of the original price?",
    choices: ["44%", "50%", "56%", "60%"],
    ans: "C",
    exp: "Successive discounts multiply: 0.70 × 0.80 = 0.56, so the final price is 56% of the original. Choice B comes from adding the discounts to get 50% off, which double-counts the amount already removed.",
  },
  {
    d: "psda",
    s: "one_var_data",
    diff: "medium",
    type: "mc",
    prompt: "Data set B is created by adding 12 to each of the values in data set A. Which of the following correctly compares the medians and the ranges of the two data sets?",
    choices: [
      "The median of B equals the median of A, and the range of B equals the range of A.",
      "The median of B is greater than the median of A, and the range of B equals the range of A.",
      "The median of B is greater than the median of A, and the range of B is greater than the range of A.",
      "The median of B equals the median of A, and the range of B is greater than the range of A.",
    ],
    ans: "B",
    exp: "Adding a constant slides every value up, so the median increases by 12. The range is a difference between two values, and both shift equally, so the difference is unchanged. Choice C wrongly assumes anything that shifts the data must also spread it.",
  },
  {
    d: "psda",
    s: "sample_stats_moe",
    diff: "hard",
    type: "mc",
    prompt: "A random sample of 200 residents of a city was surveyed, and the mean commute time was found to be 34 minutes, with an associated margin of error of 2.5 minutes at a 95% confidence level. Which statement is the most appropriate conclusion?",
    choices: [
      "Every resident of the city has a commute between 31.5 and 36.5 minutes.",
      "It is plausible that the mean commute time for all residents of the city is between 31.5 and 36.5 minutes.",
      "The mean commute time of the 200 residents surveyed is between 31.5 and 36.5 minutes.",
      "It is plausible that the mean commute time for all people in the country is between 31.5 and 36.5 minutes.",
    ],
    ans: "B",
    exp: "A margin of error describes a plausible interval for the population mean, and the population here is the residents of that city. Choice A applies an interval about an average to every individual, and choice C describes the sample, whose mean is known exactly to be 34.",
  },

  // ---- Geometry and Trigonometry (3) ----
  {
    d: "geometry_trig",
    s: "right_triangles_trig",
    diff: "medium",
    type: "mc",
    prompt: "In right triangle ABC, angle C is a right angle and sin(A) = 5/13. What is the value of cos(A)?",
    choices: ["5/12", "12/13", "13/12", "5/13"],
    ans: "B",
    exp: "If sin(A) = opposite/hypotenuse = 5/13, the third side is √(13² − 5²) = 12, so cos(A) = 12/13. Choice A is tan(A), which uses the two legs rather than a leg and the hypotenuse.",
  },
  {
    d: "geometry_trig",
    s: "circles",
    diff: "hard",
    type: "spr",
    prompt: "The equation x² + y² − 6x + 8y = 0 represents a circle in the xy-plane. What is the radius of the circle?",
    ans: "5",
    alt: ["5.0"],
    exp: "Completing the square gives (x − 3)² + (y + 4)² = 9 + 16 = 25, so the radius is √25 = 5. Answering 25 reports r² rather than r, which is the usual slip once the squares are completed.",
  },
  {
    d: "geometry_trig",
    s: "area_volume",
    diff: "hard",
    type: "mc",
    prompt: "A right circular cylinder has a volume of 96π cubic centimeters. A second cylinder has twice the radius and half the height of the first. What is the volume, in cubic centimeters, of the second cylinder?",
    choices: ["48π", "96π", "192π", "384π"],
    ans: "C",
    exp: "Volume is πr²h, so doubling the radius multiplies the volume by 4 while halving the height divides it by 2, giving a net factor of 2: 2 × 96π = 192π. Choice B assumes the two changes cancel, which ignores that the radius is squared.",
  },
];

export const MOCK2_MATH_2 = [
  // ---- Algebra (8) ----
  {
    d: "algebra",
    s: "linear_eq_one_var",
    diff: "medium",
    type: "mc",
    prompt: "If 2(x + 5) − 3(x − 1) = 4, what is the value of x?",
    choices: ["−9", "3", "9", "13"],
    ans: "C",
    exp: "Distributing gives 2x + 10 − 3x + 3 = 4, so −x + 13 = 4 and x = 9. Choice A comes from mishandling the sign when dividing by −1 at the final step.",
  },
  {
    d: "algebra",
    s: "linear_functions",
    diff: "medium",
    type: "mc",
    prompt: "What is the slope of the line that passes through the points (−2, 5) and (4, −7)?",
    choices: ["−2", "−1/2", "1/2", "2"],
    ans: "A",
    exp: "The slope is (−7 − 5)/(4 − (−2)) = −12/6 = −2. Choice B inverts the rise and the run, which is the most common error when the numbers do not divide evenly.",
  },
  {
    d: "algebra",
    s: "linear_eq_one_var",
    diff: "medium",
    type: "mc",
    prompt: "If (2x + 1)/3 + (x − 4)/2 = 3, what is the value of x?",
    choices: ["2", "3", "4", "7"],
    ans: "C",
    exp: "Multiplying through by 6 clears the fractions: 2(2x + 1) + 3(x − 4) = 18, so 4x + 2 + 3x − 12 = 18 and 7x = 28, giving x = 4. Multiplying only one term by 6 is what produces the other values.",
  },
  {
    d: "algebra",
    s: "systems_two_linear",
    diff: "hard",
    type: "mc",
    prompt: "The system of equations 6x − 4y = 10 and −9x + 6y = c has infinitely many solutions. What is the value of c?",
    choices: ["−15", "−10", "10", "15"],
    ans: "A",
    exp: "Infinitely many solutions means the two equations describe the same line. Multiplying the first equation by −3/2 gives −9x + 6y = −15, so c = −15. Choice D has the right magnitude but ignores that the multiplier is negative.",
  },
  {
    d: "algebra",
    s: "systems_two_linear",
    diff: "hard",
    type: "mc",
    prompt: "How many solutions (x, y) does the system consisting of the three equations 3x + 2y = 7, 6x + 4y = 14, and x − y = 4 have?",
    choices: ["Zero", "Exactly one", "Exactly two", "Infinitely many"],
    ans: "B",
    exp: "The second equation is exactly twice the first, so those two describe the same line rather than adding a new constraint. That line and x − y = 4 have different slopes, so they meet at exactly one point. Choice D treats the duplicated equation as if it made the whole system dependent.",
  },
  {
    d: "algebra",
    s: "systems_two_linear",
    diff: "hard",
    type: "spr",
    prompt: "If 5x − 3y = 21 and 2x + y = 4, what is the value of x + y?",
    ans: "1",
    alt: ["1.0"],
    exp: "From the second equation, y = 4 − 2x. Substituting gives 5x − 3(4 − 2x) = 21, so 11x = 33 and x = 3, which makes y = −2. Therefore x + y = 1. Stopping at x = 3 is the trap the question is built around.",
  },
  {
    d: "algebra",
    s: "linear_functions",
    diff: "hard",
    type: "mc",
    prompt: "A tank holds 500 liters of water. Water drains out at a constant 12 liters per minute while simultaneously being added at a constant 5 liters per minute. After how many minutes does the tank contain 220 liters?",
    choices: ["23", "29", "40", "70"],
    ans: "C",
    exp: "The net rate is 12 − 5 = 7 liters lost per minute, so 500 − 7t = 220 gives 7t = 280 and t = 40. Choice A uses only the draining rate and ignores the water being added.",
  },
  {
    d: "algebra",
    s: "linear_functions",
    diff: "hard",
    type: "mc",
    prompt: "The graph of the line y = mx + b passes through the points (3, −1) and (−1, 7). What is the value of m + b?",
    choices: ["−2", "3", "5", "7"],
    ans: "B",
    exp: "The slope is (7 − (−1))/(−1 − 3) = 8/(−4) = −2, and substituting (3, −1) gives −1 = −6 + b, so b = 5. Therefore m + b = 3. Choices A and C are the two components separately.",
  },

  // ---- Advanced Math (8) ----
  {
    d: "advanced_math",
    s: "nonlinear_functions",
    diff: "medium",
    type: "mc",
    prompt: "The function f is defined by f(x) = 3x² − 12x + 7. What is the x-coordinate of the vertex of the graph of y = f(x)?",
    choices: ["−2", "2", "4", "7"],
    ans: "B",
    exp: "The vertex is at x = −b/(2a) = 12/6 = 2. Choice A drops the negative sign in the formula, and choice C uses b/a without halving it.",
  },
  {
    d: "advanced_math",
    s: "equivalent_expressions",
    diff: "medium",
    type: "mc",
    prompt: "For x > 0, which expression is equivalent to x^(1/2) · x^(3/4)?",
    choices: ["x^(3/8)", "x^(5/4)", "x^(2/3)", "x^(1/4)"],
    ans: "B",
    exp: "Multiplying powers of the same base adds the exponents: 1/2 + 3/4 = 5/4. Choice A multiplies the exponents instead, and choice D subtracts them.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_eq_systems",
    diff: "hard",
    type: "spr",
    prompt: "In the equation 4x² + bx + 9 = 0, b is a positive constant and the equation has exactly one real solution. What is the value of b?",
    ans: "12",
    alt: ["12.0"],
    exp: "Exactly one real solution means the discriminant is zero: b² − 4(4)(9) = 0, so b² = 144 and b = ±12. Since b is given as positive, b = 12.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_functions",
    diff: "hard",
    type: "spr",
    prompt: "If (x − 3) is a factor of the polynomial x³ − 4x² + kx − 6, what is the value of k?",
    ans: "5",
    alt: ["5.0"],
    exp: "If (x − 3) is a factor then substituting x = 3 must give zero: 27 − 36 + 3k − 6 = 0, so 3k = 15 and k = 5. Substituting x = −3 instead, by misreading the sign of the factor, is the usual error here.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_eq_systems",
    diff: "hard",
    type: "mc",
    prompt: "The graphs of y = x² + 4x + c and y = 2x + 3 intersect at exactly one point in the xy-plane. What is the value of c?",
    choices: ["3", "4", "5", "7"],
    ans: "B",
    exp: "Setting the expressions equal gives x² + 2x + (c − 3) = 0, and exactly one intersection means the discriminant is zero: 4 − 4(c − 3) = 0, so c − 3 = 1 and c = 4. Forgetting to move 2x + 3 across before applying the discriminant produces the other choices.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_functions",
    diff: "hard",
    type: "mc",
    prompt: "A population is modeled by P(t) = 800(1.21)^(t/2), where t is the number of years since the study began. By what percent does the population increase each year?",
    choices: ["10%", "10.5%", "21%", "42%"],
    ans: "A",
    exp: "One year corresponds to t = 1, giving a factor of 1.21^(1/2) = 1.1, which is a 10% increase. Choice C reads the two-year growth factor as if it were annual, and choice B halves the percent rather than taking the square root of the factor.",
  },
  {
    d: "advanced_math",
    s: "equivalent_expressions",
    diff: "hard",
    type: "mc",
    prompt: "What is the solution to the equation 1/(x − 2) + 1/(x + 2) = 4/(x² − 4)?",
    choices: ["x = −2", "x = 0", "x = 2", "There is no solution."],
    ans: "D",
    exp: "Since x² − 4 = (x − 2)(x + 2), multiplying through by that product gives (x + 2) + (x − 2) = 4, so 2x = 4 and x = 2. But x = 2 makes the original denominators zero, so it is extraneous and the equation has no solution. Choice C is what you get by never checking the result against the original equation.",
  },
  {
    d: "advanced_math",
    s: "equivalent_expressions",
    diff: "hard",
    type: "spr",
    prompt: "If 2^(x + 2) = 40, what is the value of 2^x?",
    ans: "10",
    alt: ["10.0"],
    exp: "Since 2^(x + 2) = 2^x · 2² = 4 · 2^x, we have 4 · 2^x = 40, so 2^x = 10. No logarithms are needed — separating the exponent is enough, and dividing by 2 instead of 4 is the common slip.",
  },

  // ---- Problem-Solving and Data Analysis (3) ----
  {
    d: "psda",
    s: "evaluating_claims",
    diff: "hard",
    type: "mc",
    prompt: "A researcher surveyed 500 randomly selected students at one university and found that 62% supported a proposed policy, with an associated margin of error of 4% at a 95% confidence level. Which statement is best supported by these results?",
    choices: [
      "Exactly 62% of all students at the university support the policy.",
      "It is plausible that between 58% and 66% of all students at the university support the policy.",
      "It is plausible that between 58% and 66% of all university students in the country support the policy.",
      "Between 58% and 66% of the 500 students surveyed support the policy.",
    ],
    ans: "B",
    exp: "The interval applies to the population that was randomly sampled — students at that one university. Choice C generalises beyond the sampled population, choice A treats an estimate as exact, and choice D describes the sample, where the figure is known to be exactly 62%.",
  },
  {
    d: "psda",
    s: "one_var_data",
    diff: "hard",
    type: "mc",
    prompt: "The data set 2, 4, 4, 5, 9 is changed by replacing the value 9 with 25. Which of the following statistics changes the least?",
    choices: ["The mean", "The median", "The range", "The standard deviation"],
    ans: "B",
    exp: "The median is the middle value of the ordered list, which is 4 before and 4 after, so it does not change at all. The mean rises from 4.8 to 8, the range rises from 7 to 23, and the spread grows, so the median is uniquely resistant to a single extreme value.",
  },
  {
    d: "psda",
    s: "probability",
    diff: "hard",
    type: "spr",
    prompt: "Of 200 students surveyed, 80 play a sport and 50 of those students also play an instrument. Of the students surveyed, 30 play neither a sport nor an instrument. If a student who does not play a sport is selected at random, what is the probability that the student plays an instrument?",
    ans: "0.75",
    alt: ["3/4", ".75", "0.750"],
    exp: "Students who do not play a sport number 200 − 80 = 120, and 30 of those play neither, so 90 of them play an instrument. The probability is 90/120 = 0.75. Dividing by 200 instead of 120 ignores that the question restricts attention to non-athletes.",
  },

  // ---- Geometry and Trigonometry (3) ----
  {
    d: "geometry_trig",
    s: "right_triangles_trig",
    diff: "hard",
    type: "mc",
    prompt: "In right triangle PQR, angle Q is a right angle and sin(P) = 20/29. What is the value of cos(R)?",
    choices: ["20/29", "21/29", "29/20", "21/20"],
    ans: "A",
    exp: "Angles P and R are complementary because angle Q is the right angle, and the cosine of an angle equals the sine of its complement, so cos(R) = sin(P) = 20/29. Choice B is cos(P), found by computing the third side and answering for the wrong angle.",
  },
  {
    d: "geometry_trig",
    s: "circles",
    diff: "hard",
    type: "spr",
    prompt: "The equation x² + y² + 10x − 4y = 20 represents a circle in the xy-plane. What is the radius of the circle?",
    ans: "7",
    alt: ["7.0"],
    exp: "Completing the square gives (x + 5)² + (y − 2)² = 20 + 25 + 4 = 49, so the radius is 7. The constants added to complete each square must also be added to the right-hand side, which is the step most often missed.",
  },
  {
    d: "geometry_trig",
    s: "lines_angles_triangles",
    diff: "hard",
    type: "mc",
    prompt: "Two similar triangles have perimeters of 12 centimeters and 30 centimeters. If the area of the smaller triangle is 20 square centimeters, what is the area of the larger triangle, in square centimeters?",
    choices: ["50", "80", "125", "200"],
    ans: "C",
    exp: "The ratio of corresponding lengths is 12:30 = 2:5, and areas scale as the square of that ratio, so the area ratio is 4:25. Therefore the larger area is 20 × 25/4 = 125. Choice A applies the length ratio directly to the area, which is the standard error.",
  },
];
