// Full Mock 3 — Math, Modules 1 and 2. 22 questions per module.
//
// Per module: Algebra 8, Advanced Math 8, Problem-Solving and Data Analysis 3,
// Geometry and Trigonometry 3; exactly 6 student-produced responses (12 total).
// Module 1 is a broad easy/medium/hard mix; Module 2 is the upper module.
//
// Every item was solved by hand before being written down. No question depends
// on a figure: tables are given inline and geometry is fully described in words.

export const MOCK3_MATH_1 = [
  // ================= Algebra (8) =================
  {
    d: "algebra",
    s: "linear_eq_one_var",
    diff: "easy",
    type: "mc",
    prompt: "If 3(x − 4) = 2x + 5, what is the value of x?",
    choices: ["17", "9", "1", "−7"],
    ans: "A",
    exp: "Distribute: 3x − 12 = 2x + 5, then subtract 2x and add 12 to get x = 17. Choice B comes from forgetting to multiply the −4 by 3, and choice D from moving the −12 without changing its sign.",
  },
  {
    d: "algebra",
    s: "linear_eq_two_var",
    diff: "easy",
    type: "spr",
    prompt: "The line y = −2x + 9 passes through the point (k, 1). What is the value of k?",
    ans: "4",
    alt: ["4.0"],
    exp: "Substitute y = 1: 1 = −2k + 9, so 2k = 8 and k = 4. Substituting the 1 for x instead of y is the common slip and gives 7.",
  },
  {
    d: "algebra",
    s: "linear_functions",
    diff: "easy",
    type: "mc",
    prompt: "A phone plan costs $12 per month plus $0.05 for each text message sent. Which function gives the monthly cost C, in dollars, for t text messages?",
    choices: ["C(t) = 0.05t + 12", "C(t) = 12t + 0.05", "C(t) = 12.05t", "C(t) = 0.05(t + 12)"],
    ans: "A",
    exp: "The fixed $12 does not change with t and the $0.05 is multiplied by the number of messages, giving 0.05t + 12. Choice B swaps the roles: it would charge $12 per message.",
  },
  {
    d: "algebra",
    s: "systems_two_linear",
    diff: "medium",
    type: "mc",
    prompt: "Tickets to a school play cost $8 for students and $14 for adults. One evening, 150 tickets were sold for a total of $1,620. How many adult tickets were sold?",
    choices: ["70", "80", "60", "75"],
    ans: "A",
    exp: "With s + a = 150 and 8s + 14a = 1,620, substitute s = 150 − a: 1,200 + 6a = 1,620, so a = 70. Choice B is the number of student tickets, the other unknown; the question asks for adults.",
  },
  {
    d: "algebra",
    s: "linear_inequalities",
    diff: "hard",
    type: "spr",
    prompt: "A worker earns $15 per hour for the first 40 hours worked in a week and $22.50 per hour for each hour beyond 40. What is the minimum number of whole hours the worker must work in one week to earn at least $825?",
    ans: "50",
    alt: ["50.0"],
    exp: "The first 40 hours earn 40 × 15 = $600, leaving $225 to earn at $22.50 per hour: 225 ÷ 22.5 = 10 more hours, so 50 hours in total. Answering 10 forgets to add the first 40 hours back.",
  },
  {
    d: "algebra",
    s: "linear_functions",
    diff: "medium",
    type: "mc",
    prompt: "The function h(t) = 1,200 − 45t models the height, in meters, of a hot-air balloon t minutes after it begins to descend. Which of the following is the best interpretation of 45 in this context?",
    choices: [
      "The balloon descends 45 meters each minute.",
      "The balloon begins its descent at a height of 45 meters.",
      "The balloon reaches the ground after 45 minutes.",
      "The balloon descends a total of 45 meters.",
    ],
    ans: "A",
    exp: "In a linear model the number multiplied by t is the rate of change per unit of t, so 45 is meters per minute. The starting height is 1,200 (choice B), and the landing time is 1,200 ÷ 45, about 26.7 minutes, not 45 (choice C).",
  },
  {
    d: "algebra",
    s: "systems_two_linear",
    diff: "hard",
    type: "mc",
    prompt: "The system of equations 6x − 4y = 10 and 9x + ky = 15 has infinitely many solutions. What is the value of k?",
    choices: ["−6", "6", "−9", "4"],
    ans: "A",
    exp: "Infinitely many solutions means the equations describe the same line, so the second must be a multiple of the first: 9 is 1.5 × 6 and 15 is 1.5 × 10, so k = 1.5 × (−4) = −6. Choice B drops the sign of the −4.",
  },
  {
    d: "algebra",
    s: "linear_eq_two_var",
    diff: "hard",
    type: "spr",
    prompt: "Line ℓ is perpendicular to the line 2x + 5y = 20 and passes through the point (4, −1). What is the y-coordinate of the y-intercept of line ℓ?",
    ans: "-11",
    alt: ["-11.0"],
    exp: "Rewrite the given line as y = −(2/5)x + 4; a perpendicular line has the negative reciprocal slope, 5/2. Through (4, −1): −1 = (5/2)(4) + b, so b = −1 − 10 = −11. Using the slope −2/5 or 2/5 instead of 5/2 is the usual error.",
  },

  // ================= Advanced Math (8) =================
  {
    d: "advanced_math",
    s: "equivalent_expressions",
    diff: "easy",
    type: "mc",
    prompt: "Which expression is equivalent to (2x + 3)(x − 5)?",
    choices: ["2x² − 7x − 15", "2x² + 7x − 15", "2x² − 13x − 15", "2x² − 2x − 15"],
    ans: "A",
    exp: "Multiply each term: 2x² − 10x + 3x − 15 = 2x² − 7x − 15. Choice C comes from writing −10x − 3x instead of −10x + 3x.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_functions",
    diff: "easy",
    type: "mc",
    prompt: "The function f is defined by f(x) = x² − 4x + 1. What is the value of f(−2)?",
    choices: ["13", "−3", "5", "−11"],
    ans: "A",
    exp: "f(−2) = (−2)² − 4(−2) + 1 = 4 + 8 + 1 = 13. Choice C results from treating (−2)² as −4, and choice B from treating −4(−2) as −8.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_eq_systems",
    diff: "medium",
    type: "spr",
    prompt: "What is the positive solution to the equation x² − 5x − 24 = 0?",
    ans: "8",
    alt: ["8.0"],
    exp: "Factor into (x − 8)(x + 3) = 0, so x = 8 or x = −3, and the positive solution is 8. Reversing the signs to (x + 8)(x − 3) gives the wrong pair.",
  },
  {
    d: "advanced_math",
    s: "equivalent_expressions",
    diff: "medium",
    type: "mc",
    prompt: "For positive values of x and y, which expression is equivalent to (x⁶y³)^(1/3)?",
    choices: ["x²y", "x¹⁸y⁹", "x³y", "x^(1/2)y"],
    ans: "A",
    exp: "A power of a product applies to each factor, and exponents multiply: x^(6 × 1/3) · y^(3 × 1/3) = x²y. Choice B multiplies by 3 instead of by 1/3.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_functions",
    diff: "medium",
    type: "mc",
    prompt: "The function g is defined by g(x) = 2x² − 12x + 5. What is the minimum value of g(x)?",
    choices: ["−13", "5", "3", "−31"],
    ans: "A",
    exp: "The vertex is at x = −b/(2a) = 12/4 = 3, and g(3) = 18 − 36 + 5 = −13. Choice C is the x-coordinate of the vertex, not the minimum value, and choice B is g(0).",
  },
  {
    d: "advanced_math",
    s: "nonlinear_functions",
    diff: "medium",
    type: "mc",
    prompt: "A bacteria population starts at 500 and doubles every 3 hours. Which equation gives the population P after t hours?",
    choices: ["P = 500(2)^(t/3)", "P = 500(2)^(3t)", "P = 500(3)^(t/2)", "P = 500 + 2^(t/3)"],
    ans: "A",
    exp: "Doubling every 3 hours means the number of doublings after t hours is t/3, so P = 500 · 2^(t/3). Choice B would double the population three times every hour.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_eq_systems",
    diff: "hard",
    type: "spr",
    prompt: "The system y = x² − 2x and y = 2x − 3 has two solutions. What is the sum of the x-coordinates of the two solutions?",
    ans: "4",
    alt: ["4.0"],
    exp: "Set the expressions equal: x² − 2x = 2x − 3, so x² − 4x + 3 = 0, which factors as (x − 1)(x − 3). The x-coordinates are 1 and 3, with sum 4. Reporting a y-coordinate or just one solution is the common slip.",
  },
  {
    d: "advanced_math",
    s: "equivalent_expressions",
    diff: "hard",
    type: "mc",
    prompt: "For x ≠ 2 and x ≠ −3, which expression is equivalent to (x² − 9) / (x² + x − 6)?",
    choices: ["(x − 3) / (x − 2)", "(x + 3) / (x − 2)", "(x − 3) / (x + 3)", "(x + 3) / (x + 2)"],
    ans: "A",
    exp: "Factor both: (x − 3)(x + 3) over (x + 3)(x − 2); the (x + 3) cancels, leaving (x − 3)/(x − 2). Choice B keeps the factor that cancels and drops the one that stays.",
  },

  // ================= Problem-Solving and Data Analysis (3) =================
  {
    d: "psda",
    s: "percentages",
    diff: "easy",
    type: "mc",
    prompt: "A store sets the retail price of each item at 60% above its wholesale cost. A lamp has a wholesale cost of $45. What is its retail price?",
    choices: ["$72", "$27", "$105", "$75"],
    ans: "A",
    exp: "60% of 45 is 27, and the retail price is 45 + 27 = $72, or 1.6 × 45 directly. Choice B is the markup alone, not the price.",
  },
  {
    d: "psda",
    s: "one_var_data",
    diff: "hard",
    type: "mc",
    prompt: "The ages of the 7 members of a chess club are 12, 13, 13, 14, 15, 17, and 21. If the 21-year-old leaves the club, which statistic for the remaining members changes by the greatest amount?",
    choices: ["Mean", "Median", "Mode", "Range"],
    ans: "D",
    exp: "The range falls from 21 − 12 = 9 to 17 − 12 = 5, a change of 4. The mean drops from 15 to 14 (a change of 1), the median from 14 to 13.5, and the mode stays 13. Removing an extreme value always hits the range hardest.",
  },
  {
    d: "psda",
    s: "probability",
    diff: "medium",
    type: "mc",
    prompt: "A bag contains only red and blue marbles. The probability of drawing a red marble at random is 3/8. If there are 15 red marbles, how many blue marbles are in the bag?",
    choices: ["25", "24", "40", "9"],
    ans: "A",
    exp: "If 15 red marbles are 3/8 of the bag, the bag holds 15 ÷ (3/8) = 40 marbles, so 40 − 15 = 25 are blue. Choice C is the total, not the number of blue marbles.",
  },

  // ================= Geometry and Trigonometry (3) =================
  {
    d: "geometry_trig",
    s: "area_volume",
    diff: "easy",
    type: "mc",
    prompt: "A rectangular tank is 40 centimeters long, 25 centimeters wide, and 30 centimeters tall. Water fills the tank to a depth of 18 centimeters. What is the volume of the water, in cubic centimeters?",
    choices: ["18,000", "30,000", "12,000", "1,800"],
    ans: "A",
    exp: "The water forms a box 40 by 25 by 18, so its volume is 40 × 25 × 18 = 18,000. Choice B uses the full height of 30 instead of the water's depth.",
  },
  {
    d: "geometry_trig",
    s: "lines_angles_triangles",
    diff: "easy",
    type: "mc",
    prompt: "In triangle ABC, the measure of angle A is 30°, and the measure of angle B is twice the measure of angle C. What is the measure of angle B?",
    choices: ["100°", "50°", "75°", "120°"],
    ans: "A",
    exp: "Angles B and C share the remaining 150°, and B = 2C, so 3C = 150 and C = 50°, making B = 100°. Choice B is angle C, the other unknown.",
  },
  {
    d: "geometry_trig",
    s: "right_triangles_trig",
    diff: "hard",
    type: "spr",
    prompt: "In right triangle PQR, angle Q is the right angle, PQ = 8, and QR = 15. What is the value of sin P?",
    ans: "15/17",
    alt: [".8823", "0.8823", ".8824", "0.8824"],
    exp: "The hypotenuse PR is √(8² + 15²) = 17. Sine is opposite over hypotenuse, and the side opposite angle P is QR = 15, so sin P = 15/17. Using the adjacent side gives 8/17, which is cos P.",
  },
];

export const MOCK3_MATH_2 = [
  // ================= Algebra (8) =================
  {
    d: "algebra",
    s: "linear_eq_one_var",
    diff: "easy",
    type: "mc",
    prompt: "If x/4 + 7 = 12, what is the value of x?",
    choices: ["20", "76", "5", "48"],
    ans: "A",
    exp: "Subtract 7 to get x/4 = 5, then multiply by 4: x = 20. Choice B multiplies both 12 and 7 by 4 and adds; choice C stops at x/4 = 5.",
  },
  {
    d: "algebra",
    s: "linear_eq_two_var",
    diff: "medium",
    type: "mc",
    prompt: "Which equation represents the line that passes through the points (−3, 8) and (1, 0)?",
    choices: ["y = −2x + 2", "y = 2x + 14", "y = −2x − 2", "y = −(1/2)x + 1/2"],
    ans: "A",
    exp: "The slope is (0 − 8)/(1 − (−3)) = −8/4 = −2, and through (1, 0): 0 = −2(1) + b, so b = 2. Choice C has the right slope but the wrong intercept; check it against (1, 0), where it gives −4.",
  },
  {
    d: "algebra",
    s: "linear_functions",
    diff: "medium",
    type: "spr",
    prompt: "The function f is linear, with f(2) = 9 and f(6) = 1. What is the value of f(0)?",
    ans: "13",
    alt: ["13.0"],
    exp: "The slope is (1 − 9)/(6 − 2) = −2, so moving from x = 2 back to x = 0 adds 2 × 2 = 4 to the output: f(0) = 9 + 4 = 13. Subtracting instead of adding gives 5.",
  },
  {
    d: "algebra",
    s: "systems_two_linear",
    diff: "medium",
    type: "mc",
    prompt: "If x + 2y = 11 and 3x − y = 5, what is the value of x + y?",
    choices: ["7", "3", "4", "1"],
    ans: "A",
    exp: "From the second equation y = 3x − 5; substituting gives x + 6x − 10 = 11, so x = 3 and y = 4, and x + y = 7. Choices B and C are x and y alone, but the question asks for their sum.",
  },
  {
    d: "algebra",
    s: "linear_inequalities",
    diff: "medium",
    type: "mc",
    prompt: "A bakery can make at most 120 loaves in a day. Each sourdough loaf uses 2 units of flour and each rye loaf uses 3 units, and 300 units of flour are available. If s is the number of sourdough loaves and r is the number of rye loaves, which system of inequalities represents these constraints?",
    choices: [
      "s + r ≤ 120 and 2s + 3r ≤ 300",
      "s + r ≥ 120 and 2s + 3r ≤ 300",
      "s + r ≤ 120 and 3s + 2r ≤ 300",
      "2s + 3r ≤ 120 and s + r ≤ 300",
    ],
    ans: "A",
    exp: "'At most 120 loaves' is s + r ≤ 120, and the flour used, 2s + 3r, cannot exceed 300. Choice C swaps the flour amounts, and choice D attaches each limit to the wrong quantity.",
  },
  {
    d: "algebra",
    s: "linear_eq_one_var",
    diff: "hard",
    type: "spr",
    prompt: "In the equation 4(x + a) = 4x + 18 − 2a, a is a constant. If the equation has infinitely many solutions, what is the value of a?",
    ans: "3",
    alt: ["3.0"],
    exp: "Expand: 4x + 4a = 4x + 18 − 2a. The 4x terms match, so the equation is true for every x exactly when 4a = 18 − 2a, giving 6a = 18 and a = 3. Any other a makes the equation false for all x.",
  },
  {
    d: "algebra",
    s: "linear_functions",
    diff: "medium",
    type: "mc",
    prompt: "The total cost y, in dollars, of renting a hall for x hours is modeled by y = 85x + 240. Which of the following is the best interpretation of 240 in this context?",
    choices: [
      "The fixed fee charged regardless of the number of hours",
      "The cost of each additional hour",
      "The maximum number of hours the hall can be rented",
      "The total cost of renting the hall for one hour",
    ],
    ans: "A",
    exp: "When x = 0 the cost is 240, so it is the charge before any hours are counted: a fixed fee. The hourly cost is 85 (choice B), and one hour costs 85 + 240 = 325 (choice D).",
  },
  {
    d: "algebra",
    s: "systems_two_linear",
    diff: "hard",
    type: "mc",
    prompt: "The system of equations 3x − 2y = 7 and ax + 6y = b, where a and b are constants, has no solution. Which of the following must be true?",
    choices: [
      "a = −9 and b ≠ −21",
      "a = −9 and b = −21",
      "a = 9 and b ≠ 21",
      "a = 9 and b = 21",
    ],
    ans: "A",
    exp: "No solution means parallel lines: the same slope but different intercepts. Multiplying the first equation by −3 gives −9x + 6y = −21, so a must be −9, and b must NOT be −21, or the lines would coincide and have infinitely many solutions (choice B).",
  },

  // ================= Advanced Math (8) =================
  {
    d: "advanced_math",
    s: "nonlinear_functions",
    diff: "easy",
    type: "mc",
    prompt: "In the xy-plane, what is the y-intercept of the graph of y = (x − 2)(x + 5)?",
    choices: ["(0, −10)", "(0, 10)", "(0, 3)", "(0, −3)"],
    ans: "A",
    exp: "Set x = 0: y = (−2)(5) = −10. Choice C adds the constants (−2 + 5) instead of multiplying them.",
  },
  {
    d: "advanced_math",
    s: "equivalent_expressions",
    diff: "medium",
    type: "mc",
    prompt: "Which expression is equivalent to (3x² − 5x + 2) − (x² − 7x − 4)?",
    choices: ["2x² + 2x + 6", "2x² − 12x − 2", "2x² + 2x − 2", "4x² − 12x − 2"],
    ans: "A",
    exp: "Subtracting the second polynomial flips every sign in it: 3x² − 5x + 2 − x² + 7x + 4 = 2x² + 2x + 6. Choice B forgets to flip the signs of −7x and −4.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_eq_systems",
    diff: "easy",
    type: "spr",
    prompt: "If √(2x + 7) = 5, what is the value of x?",
    ans: "9",
    alt: ["9.0"],
    exp: "Square both sides: 2x + 7 = 25, so 2x = 18 and x = 9. Checking, √(18 + 7) = √25 = 5. Forgetting to square and solving 2x + 7 = 5 gives −1.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_functions",
    diff: "medium",
    type: "mc",
    prompt: "The value V, in dollars, of a car t years after it was purchased is modeled by V(t) = 28,000(0.85)^t. By what percent does the car's value decrease each year?",
    choices: ["15%", "85%", "28%", "1.5%"],
    ans: "A",
    exp: "Each year the value is multiplied by 0.85, which keeps 85% and removes the other 15%. Choice B is the trap: 85% is what remains, not what is lost.",
  },
  {
    d: "advanced_math",
    s: "equivalent_expressions",
    diff: "hard",
    type: "spr",
    prompt: "The expression x² + bx + 36, where b is a negative constant, is equivalent to (x − c)² for some constant c. What is the value of b?",
    ans: "-12",
    alt: ["-12.0"],
    exp: "(x − c)² = x² − 2cx + c², so c² = 36 and c = 6 (taking c positive makes b negative), giving b = −2c = −12. Answering −6 forgets the factor of 2 in the middle term.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_eq_systems",
    diff: "hard",
    type: "mc",
    prompt: "How many distinct real solutions does the equation 2x² − 3x + 5 = 0 have?",
    choices: ["Zero", "One", "Two", "Infinitely many"],
    ans: "A",
    exp: "The discriminant b² − 4ac = 9 − 40 = −31 is negative, so there are no real solutions. Choice C is the usual guess for any quadratic, but a quadratic has two real solutions only when the discriminant is positive.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_functions",
    diff: "hard",
    type: "mc",
    prompt: "The graph of the quadratic function f has its vertex at (1, −4). The function g is defined by g(x) = f(x − 3) + 2. What are the coordinates of the vertex of the graph of g?",
    choices: ["(4, −2)", "(−2, −2)", "(4, −6)", "(−2, −6)"],
    ans: "A",
    exp: "Replacing x with x − 3 shifts the graph 3 units to the right, and adding 2 shifts it up 2, moving the vertex to (1 + 3, −4 + 2) = (4, −2). Choice B shifts left, the trap set by the minus sign inside the parentheses.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_eq_systems",
    diff: "hard",
    type: "spr",
    prompt: "The system x² + y² = 25 and y = x + 1 has two solutions. What is the greater of the two x-coordinates?",
    ans: "3",
    alt: ["3.0"],
    exp: "Substitute: x² + (x + 1)² = 25, so 2x² + 2x − 24 = 0, or x² + x − 12 = 0, which factors as (x + 4)(x − 3). The x-coordinates are −4 and 3, and the greater is 3. Dropping the (x + 1)² expansion's middle term is the usual error.",
  },

  // ================= Problem-Solving and Data Analysis (3) =================
  {
    d: "psda",
    s: "percentages",
    diff: "medium",
    type: "mc",
    prompt: "After an 18% price increase, a monthly transit pass costs $59. What was the price of the pass before the increase?",
    choices: ["$50.00", "$48.38", "$41.00", "$69.62"],
    ans: "A",
    exp: "The new price is 118% of the old one, so the old price is 59 ÷ 1.18 = $50. Choice B subtracts 18% of 59 from 59, which undoes the wrong amount; a percent increase is reversed by dividing, not by subtracting.",
  },
  {
    d: "psda",
    s: "two_var_data",
    diff: "hard",
    type: "mc",
    prompt: "Five students recorded the hours they studied for a test and their scores.\n\nHours | Score\n1 | 62\n2 | 70\n3 | 74\n4 | 82\n5 | 88\n\nThe line of best fit for the data is y = 6.4x + 56, where x is hours studied and y is the score. How much greater or less is the actual score of the student who studied 3 hours than the score predicted by the line of best fit?",
    choices: ["1.2 points less", "1.2 points greater", "3.2 points less", "19.2 points greater"],
    ans: "A",
    exp: "The line predicts 6.4(3) + 56 = 75.2 for 3 hours, and the actual score was 74, which is 1.2 points less. Choice D is 6.4 × 3, the slope's contribution alone, not the gap between the actual and predicted scores.",
  },
  {
    d: "psda",
    s: "evaluating_claims",
    diff: "hard",
    type: "mc",
    prompt: "A researcher wants to estimate the mean daily commute time of the 200,000 workers in a city and plans to survey 500 of them. Which method of choosing the 500 workers is most likely to produce a sample that represents all workers in the city?",
    choices: [
      "Selecting 500 workers at random from a list of all workers in the city",
      "Surveying 500 workers as they leave one downtown train station",
      "Posting an online survey and using the first 500 responses received",
      "Surveying 500 workers employed by the city's largest company",
    ],
    ans: "A",
    exp: "Only a random selection from the whole population gives every worker the same chance of being chosen. The other methods each favor one group, such as train commuters or one employer, so their mean would describe that group, not the city.",
  },

  // ================= Geometry and Trigonometry (3) =================
  {
    d: "geometry_trig",
    s: "circles",
    diff: "easy",
    type: "mc",
    prompt: "In the xy-plane, a circle has the equation (x − 3)² + (y + 2)² = 49. What is the radius of the circle?",
    choices: ["7", "49", "3", "2"],
    ans: "A",
    exp: "In (x − h)² + (y − k)² = r², the right side is the radius squared, so r = √49 = 7. Choice B forgets to take the square root.",
  },
  {
    d: "geometry_trig",
    s: "area_volume",
    diff: "hard",
    type: "spr",
    prompt: "A right circular cylinder has a volume of 500π cubic centimeters and a height of 20 centimeters. What is the radius of the cylinder, in centimeters?",
    ans: "5",
    alt: ["5.0"],
    exp: "Volume is πr²h, so 500π = πr²(20); dividing by 20π gives r² = 25 and r = 5. Forgetting to take the square root gives 25.",
  },
  {
    d: "geometry_trig",
    s: "right_triangles_trig",
    diff: "hard",
    type: "mc",
    prompt: "In a right triangle, one of the acute angles has measure θ, and cos θ = 7/25. What is the value of tan θ?",
    choices: ["24/7", "7/24", "24/25", "25/7"],
    ans: "A",
    exp: "If the adjacent side is 7 and the hypotenuse is 25, the opposite side is √(625 − 49) = 24, so tan θ = opposite/adjacent = 24/7. Choice B inverts the ratio, and choice C is sin θ.",
  },
];
