// Full Mock 1 — Math, Modules 1 and 2. 22 questions each.
// Domain mix per official weightings: Algebra 8, Advanced Math 8, PSDA 3, Geometry/Trig 3.
// About one quarter are student-produced responses. All items are original.

export const MOCK_MATH_1 = [
  // ---- Algebra (8) ----
  {
    d: "algebra",
    s: "linear_eq_one_var",
    diff: "easy",
    type: "mc",
    prompt: "If 3x + 7 = 25, what is the value of x?",
    choices: ["4", "6", "8", "32/3"],
    ans: "B",
    exp: "Subtract 7 from both sides to get 3x = 18, then divide by 3 to get x = 6. Choice D comes from dividing 32 by 3 after adding 7 instead of subtracting it.",
  },
  {
    d: "algebra",
    s: "linear_eq_two_var",
    diff: "easy",
    type: "mc",
    prompt:
      "A line in the xy-plane has slope 3 and passes through the point (0, −2). Which equation represents the line?",
    choices: ["y = 3x − 2", "y = −2x + 3", "y = 3x + 2", "y = x/3 − 2"],
    ans: "A",
    exp: "Slope-intercept form is y = mx + b, and a point with x = 0 gives the y-intercept directly, so m = 3 and b = −2. Choice B swaps the slope and the intercept, a common mix-up when reading the point.",
  },
  {
    d: "algebra",
    s: "linear_eq_one_var",
    diff: "easy",
    type: "spr",
    prompt: "If 5(x − 2) = 35, what is the value of x?",
    ans: "9",
    alt: ["9.0"],
    exp: "Divide both sides by 5 to get x − 2 = 7, then add 2 to get x = 9. Distributing first gives 5x − 10 = 35 and the same result; forgetting to distribute the 5 across the −2 is what produces 7.",
  },
  {
    d: "algebra",
    s: "linear_functions",
    diff: "medium",
    type: "mc",
    prompt:
      "The linear function f satisfies f(2) = 11 and f(5) = 23. What is the value of f(8)?",
    choices: ["29", "31", "35", "38"],
    ans: "C",
    exp: "The slope is (23 − 11)/(5 − 2) = 4, so each unit increase in x adds 4, and from x = 5 to x = 8 the value rises by 12 to 35. Choice A comes from adding only a single step of 4 twice instead of three times.",
  },
  {
    d: "algebra",
    s: "systems_two_linear",
    diff: "medium",
    type: "mc",
    prompt: "If 2x + y = 11 and x − y = 1, what is the value of y?",
    choices: ["2", "3", "4", "5"],
    ans: "B",
    exp: "Adding the equations eliminates y: 3x = 12, so x = 4, and substituting into x − y = 1 gives y = 3. Choice C is the value of x, which is the most common slip when the question asks for the other variable.",
  },
  {
    d: "algebra",
    s: "linear_inequalities",
    diff: "medium",
    type: "spr",
    prompt: "What is the greatest integer value of x that satisfies 4x + 9 ≤ 33?",
    ans: "6",
    alt: ["6.0"],
    exp: "Subtracting 9 gives 4x ≤ 24, so x ≤ 6, and 6 itself satisfies the inequality because the sign is 'less than or equal to'. Answering 5 treats the inequality as strict.",
  },
  {
    d: "algebra",
    s: "systems_two_linear",
    diff: "hard",
    type: "mc",
    prompt:
      "The system 3x + ky = 7 and 6x + 8y = 5 has no solution. What is the value of k?",
    choices: ["2", "4", "8", "16"],
    ans: "B",
    exp: "No solution means the lines are parallel, so the coefficients must be proportional: 6/3 = 2, and k must satisfy 8/k = 2, giving k = 4. The constants 7 and 5 are not in that ratio, which is what makes the system inconsistent rather than identical.",
  },
  {
    d: "algebra",
    s: "linear_eq_one_var",
    diff: "hard",
    type: "mc",
    prompt:
      "A car service charges a fixed fee of $3.50 plus $1.75 for each mile travelled. What is the greatest whole number of miles a rider can travel for at most $30.00?",
    choices: ["14", "15", "16", "17"],
    ans: "B",
    exp: "Solve 3.50 + 1.75m ≤ 30, so 1.75m ≤ 26.50 and m ≤ 15.14, and the greatest whole number is 15. Choice C comes from rounding 15.14 up, but a 16th mile would push the fare past the $30 limit.",
  },

  // ---- Advanced Math (8) ----
  {
    d: "advanced_math",
    s: "equivalent_expressions",
    diff: "easy",
    type: "mc",
    prompt: "Which expression is equivalent to (x + 3)(x − 5)?",
    choices: ["x² − 2x − 15", "x² + 2x − 15", "x² − 15", "x² − 2x + 15"],
    ans: "A",
    exp: "Expanding gives x² − 5x + 3x − 15 = x² − 2x − 15. Choice D keeps the constant positive, which would require both signs in the factors to match.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_functions",
    diff: "easy",
    type: "mc",
    prompt: "If f(x) = x² − 4, what is the value of f(−3)?",
    choices: ["−13", "5", "13", "−5"],
    ans: "B",
    exp: "Squaring −3 gives 9, and 9 − 4 = 5. Choice A results from computing −(3²) − 4, which drops the parentheses around the negative input.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_eq_systems",
    diff: "medium",
    type: "mc",
    prompt: "What is the larger solution to x² − 7x + 12 = 0?",
    choices: ["2", "3", "4", "6"],
    ans: "C",
    exp: "The expression factors as (x − 3)(x − 4), so the solutions are 3 and 4 and the larger is 4. Choice B is the smaller root, which is the answer to a different question.",
  },
  {
    d: "advanced_math",
    s: "equivalent_expressions",
    diff: "medium",
    type: "spr",
    prompt: "If 2^(x + 1) = 32, what is the value of x?",
    ans: "4",
    alt: ["4.0"],
    exp: "Since 32 = 2⁵, the exponents must match: x + 1 = 5, so x = 4. Answering 5 stops one step early by solving for the exponent rather than for x.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_functions",
    diff: "medium",
    type: "mc",
    prompt:
      "The function g is defined by g(x) = (x − 4)² + 2. What is the minimum value of g?",
    choices: ["−4", "0", "2", "4"],
    ans: "C",
    exp: "A squared term is never negative, so g is smallest when (x − 4)² = 0, which happens at x = 4 and leaves g = 2. Choice D reports the x-value at which the minimum occurs rather than the minimum value itself.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_eq_systems",
    diff: "hard",
    type: "mc",
    prompt:
      "The equation x² + bx + 49 = 0, where b is a positive constant, has exactly one real solution. What is the value of b?",
    choices: ["7", "14", "49", "98"],
    ans: "B",
    exp: "Exactly one real solution means the discriminant is zero: b² − 4(1)(49) = 0, so b² = 196 and b = 14 since b is positive. Choice A takes the square root of 49 instead of solving the discriminant condition.",
  },
  {
    d: "advanced_math",
    s: "equivalent_expressions",
    diff: "hard",
    type: "spr",
    prompt: "If (x² − 9)/(x − 3) = 12 and x ≠ 3, what is the value of x?",
    ans: "9",
    alt: ["9.0"],
    exp: "Factoring the numerator as (x − 3)(x + 3) and cancelling the common factor leaves x + 3 = 12, so x = 9. Cross-multiplying without factoring leads to a quadratic whose extraneous root is the excluded value x = 3.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_functions",
    diff: "hard",
    type: "mc",
    prompt:
      "A bacterial culture starts with 400 cells and doubles every 6 hours. Which function gives the number of cells after t hours?",
    choices: ["P(t) = 400 · 2^(6t)", "P(t) = 400 · 2^(t/6)", "P(t) = 400 · 6^(t/2)", "P(t) = 400 + 2t/6"],
    ans: "B",
    exp: "Each doubling period is 6 hours, so the number of doublings after t hours is t/6 and the factor is 2^(t/6). Choice A multiplies rather than divides by 6, which would make the culture double every 10 minutes.",
  },

  // ---- Problem-Solving and Data Analysis (3) ----
  {
    d: "psda",
    s: "percentages",
    diff: "easy",
    type: "mc",
    prompt:
      "A jacket priced at $80 is increased in price by 15 percent. What is the new price?",
    choices: ["$88.00", "$92.00", "$95.00", "$120.00"],
    ans: "B",
    exp: "Fifteen percent of 80 is 12, so the new price is 80 + 12 = $92. Choice A uses 10 percent instead of 15.",
  },
  {
    d: "psda",
    s: "ratios_rates_proportions",
    diff: "medium",
    type: "spr",
    prompt:
      "A dough recipe uses flour and water in a ratio of 3 to 5 by weight. If a baker uses 18 kilograms of flour, how many kilograms of water are needed?",
    ans: "30",
    alt: ["30.0"],
    exp: "Eighteen kilograms of flour is 6 times the 3 parts in the ratio, so the water is 6 × 5 = 30 kilograms. Answering 10.8 comes from applying the ratio in reverse, treating flour as the larger share.",
  },
  {
    d: "psda",
    s: "sample_stats_moe",
    diff: "hard",
    type: "mc",
    prompt:
      "A random sample of 900 residents found that 46 percent support a proposal, with a margin of error of 3 percentage points at the 95 percent confidence level. Which conclusion is best supported?",
    choices: [
      "Exactly 46 percent of all residents support the proposal.",
      "It is plausible that support among all residents is between 43 and 49 percent.",
      "A majority of residents support the proposal.",
      "Increasing the sample size would necessarily raise the reported support.",
    ],
    ans: "B",
    exp: "A margin of error defines an interval of plausible values for the population figure, here 46 ± 3 percent. Choice C is wrong because the entire interval lies below 50 percent, and choice A treats a sample estimate as an exact population value.",
  },

  // ---- Geometry and Trigonometry (3) ----
  {
    d: "geometry_trig",
    s: "lines_angles_triangles",
    diff: "easy",
    type: "mc",
    prompt:
      "In a triangle, two of the interior angles measure 40° and 65°. What is the measure of the third angle?",
    choices: ["65°", "75°", "85°", "105°"],
    ans: "B",
    exp: "The interior angles of a triangle sum to 180°, so the third angle is 180 − 40 − 65 = 75°. Choice D is the sum of the two given angles rather than the remainder.",
  },
  {
    d: "geometry_trig",
    s: "circles",
    diff: "medium",
    type: "spr",
    prompt: "A circle has an area of 36π square centimetres. What is its radius, in centimetres?",
    ans: "6",
    alt: ["6.0"],
    exp: "Area is πr², so r² = 36 and r = 6. Answering 18 halves the area's coefficient as though the formula were linear in r.",
  },
  {
    d: "geometry_trig",
    s: "right_triangles_trig",
    diff: "hard",
    type: "mc",
    prompt:
      "In right triangle ABC, angle C measures 90°, sin A = 0.6, and the hypotenuse AB has length 20. What is the length of BC?",
    choices: ["8", "12", "16", "20"],
    ans: "B",
    exp: "Side BC is opposite angle A, and sin A = opposite/hypotenuse, so BC = 0.6 × 20 = 12. Choice C is AC, the adjacent side, found from cos A = 0.8.",
  },
];

export const MOCK_MATH_2 = [
  // ---- Algebra (8) ----
  {
    d: "algebra",
    s: "linear_eq_one_var",
    diff: "easy",
    type: "mc",
    prompt: "If 7 − 2x = 1, what is the value of x?",
    choices: ["−3", "3", "4", "−4"],
    ans: "B",
    exp: "Subtracting 7 gives −2x = −6, and dividing by −2 gives x = 3. Choice A drops one of the two negative signs when dividing.",
  },
  {
    d: "algebra",
    s: "linear_functions",
    diff: "easy",
    type: "mc",
    prompt:
      "A phone plan costs $12 per month plus $0.05 per minute of calls. Which function gives the monthly cost C, in dollars, for m minutes?",
    choices: ["C(m) = 12m + 0.05", "C(m) = 0.05m + 12", "C(m) = 12.05m", "C(m) = 12 + 5m"],
    ans: "B",
    exp: "The fixed $12 is the constant term and the per-minute charge multiplies the variable, giving C(m) = 0.05m + 12. Choice A swaps the roles of the fixed fee and the rate.",
  },
  {
    d: "algebra",
    s: "linear_eq_two_var",
    diff: "easy",
    type: "spr",
    prompt:
      "The line y = 2x + b passes through the point (3, 10). What is the value of b?",
    ans: "4",
    alt: ["4.0"],
    exp: "Substituting gives 10 = 2(3) + b, so b = 10 − 6 = 4. Answering 16 adds 6 instead of subtracting it.",
  },
  {
    d: "algebra",
    s: "linear_inequalities",
    diff: "medium",
    type: "mc",
    prompt: "Which value of x satisfies −3x + 5 > 14?",
    choices: ["−4", "−3", "0", "3"],
    ans: "A",
    exp: "Subtracting 5 gives −3x > 9, and dividing by −3 reverses the inequality to x < −3, so only −4 works. Choice B fails because x = −3 gives exactly 14, not more than 14.",
  },
  {
    d: "algebra",
    s: "systems_two_linear",
    diff: "medium",
    type: "spr",
    prompt:
      "At a stall, 2 mangoes and 3 oranges cost 130 birr, and 2 mangoes and 1 orange cost 90 birr. What is the cost, in birr, of one orange?",
    ans: "20",
    alt: ["20.0"],
    exp: "Subtracting the second equation from the first eliminates the mangoes: 2 oranges cost 40 birr, so one orange costs 20. Substituting back gives a mango at 35 birr, which checks against both equations.",
  },
  {
    d: "algebra",
    s: "linear_functions",
    diff: "medium",
    type: "mc",
    prompt:
      "The function h is linear, h(0) = −5, and h(4) = 7. What is the slope of the graph of h?",
    choices: ["1/3", "3", "12", "−3"],
    ans: "B",
    exp: "Slope is the change in output over the change in input: (7 − (−5))/(4 − 0) = 12/4 = 3. Choice C reports the change in output alone without dividing by the change in input.",
  },
  {
    d: "algebra",
    s: "linear_eq_two_var",
    diff: "hard",
    type: "mc",
    prompt:
      "In the xy-plane, line ℓ is perpendicular to the line 2x + 3y = 12 and passes through the origin. Which equation represents line ℓ?",
    choices: ["y = (3/2)x", "y = (−2/3)x", "y = (−3/2)x", "y = (2/3)x"],
    ans: "A",
    exp: "Rewriting gives y = (−2/3)x + 4, so the perpendicular slope is the negative reciprocal, 3/2, and passing through the origin makes the intercept 0. Choice B repeats the original slope instead of inverting and negating it.",
  },
  {
    d: "algebra",
    s: "systems_two_linear",
    diff: "hard",
    type: "mc",
    prompt:
      "A chemist mixes a 20 percent acid solution with a 50 percent acid solution to make 30 litres of a 30 percent solution. How many litres of the 50 percent solution are used?",
    choices: ["8", "10", "12", "20"],
    ans: "B",
    exp: "If x litres are 50 percent, then 0.5x + 0.2(30 − x) = 0.3(30) = 9, giving 0.3x = 3 and x = 10. Choice D is the volume of the weaker solution, which is 30 − 10 = 20 litres.",
  },

  // ---- Advanced Math (8) ----
  {
    d: "advanced_math",
    s: "equivalent_expressions",
    diff: "easy",
    type: "mc",
    prompt: "Which expression is equivalent to 4x² + 12x?",
    choices: ["4x(x + 3)", "4(x² + 12x)", "x(4x + 12x)", "4x(x + 12)"],
    ans: "A",
    exp: "The greatest common factor of both terms is 4x, and dividing gives x + 3, so the factored form is 4x(x + 3). Choice B factors only the 4 out of the first term and leaves the second unchanged.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_functions",
    diff: "easy",
    type: "mc",
    prompt: "If f(x) = 2x² + 1, what is f(3) − f(1)?",
    choices: ["8", "12", "16", "19"],
    ans: "C",
    exp: "f(3) = 2(9) + 1 = 19 and f(1) = 2(1) + 1 = 3, so the difference is 16. Choice D is f(3) alone, which forgets to subtract.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_eq_systems",
    diff: "medium",
    type: "mc",
    prompt: "What are the solutions to x² = 6x?",
    choices: ["x = 6 only", "x = 0 and x = 6", "x = 0 only", "x = ±√6"],
    ans: "B",
    exp: "Rewriting as x² − 6x = 0 and factoring gives x(x − 6) = 0, so x = 0 or x = 6. Choice A is the result of dividing both sides by x, which silently discards the solution x = 0.",
  },
  {
    d: "advanced_math",
    s: "equivalent_expressions",
    diff: "medium",
    type: "spr",
    prompt: "If √(x + 7) = 5, what is the value of x?",
    ans: "18",
    alt: ["18.0"],
    exp: "Squaring both sides gives x + 7 = 25, so x = 18, and checking confirms √25 = 5. Answering 32 comes from adding 7 after squaring instead of subtracting it.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_functions",
    diff: "medium",
    type: "mc",
    prompt:
      "The graph of y = x² − 6x + 5 crosses the x-axis at two points. What is the distance between them?",
    choices: ["1", "4", "5", "6"],
    ans: "B",
    exp: "Factoring gives (x − 1)(x − 5), so the intercepts are at x = 1 and x = 5 and the distance is 4. Choice C is one of the intercepts rather than the gap between them.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_functions",
    diff: "hard",
    type: "spr",
    prompt:
      "A ball is thrown upward and its height in metres after t seconds is h(t) = −5t² + 20t. After how many seconds does it return to the ground?",
    ans: "4",
    alt: ["4.0"],
    exp: "Setting h(t) = 0 gives −5t(t − 4) = 0, so t = 0 at launch and t = 4 on landing. Answering 2 gives the time of maximum height, which is halfway through the flight.",
  },
  {
    d: "advanced_math",
    s: "nonlinear_eq_systems",
    diff: "hard",
    type: "mc",
    prompt:
      "The system y = x² − 3 and y = 2x has how many real solutions?",
    choices: ["0", "1", "2", "Infinitely many"],
    ans: "C",
    exp: "Setting the expressions equal gives x² − 2x − 3 = 0, whose discriminant is 4 + 12 = 16 > 0, so there are two distinct real solutions (x = −1 and x = 3). Choice B would require the discriminant to be exactly zero, meaning the line is tangent to the parabola.",
  },
  {
    d: "advanced_math",
    s: "equivalent_expressions",
    diff: "hard",
    type: "mc",
    prompt:
      "Which expression is equivalent to (3x²y³)² / (9x y⁴)?",
    choices: ["x³y²", "x³y²/3", "9x³y²", "x⁴y²"],
    ans: "A",
    exp: "The numerator squares to 9x⁴y⁶, and dividing by 9xy⁴ cancels the 9 and subtracts exponents to give x³y². Choice C forgets that the 9 in the denominator cancels the 9 produced by squaring the 3.",
  },

  // ---- Problem-Solving and Data Analysis (3) ----
  {
    d: "psda",
    s: "probability",
    diff: "easy",
    type: "mc",
    prompt:
      "A bag contains 5 red, 7 blue, and 8 green marbles. If one marble is drawn at random, what is the probability that it is blue?",
    choices: ["7/20", "7/13", "1/3", "13/20"],
    ans: "A",
    exp: "There are 20 marbles in total and 7 are blue, so the probability is 7/20. Choice B leaves the blue marbles out of the denominator, comparing blue to non-blue instead of to the whole.",
  },
  {
    d: "psda",
    s: "one_var_data",
    diff: "medium",
    type: "spr",
    prompt:
      "The list of values 4, 7, 7, 9, 13 has a mean of m and a median of d. What is the value of m − d?",
    ans: "1",
    alt: ["1.0"],
    exp: "The five values sum to 40, so the mean is 8, and the middle value of the ordered list is 7, so m − d = 1. Answering 0 usually means the median was computed as the mean of the two central values, which applies only to an even-sized list.",
  },
  {
    d: "psda",
    s: "percentages",
    diff: "hard",
    type: "mc",
    prompt:
      "After a 20 percent discount, a bicycle sells for $340. What was its price before the discount?",
    choices: ["$408", "$408.50", "$425", "$680"],
    ans: "C",
    exp: "The sale price is 80 percent of the original, so the original is 340 ÷ 0.8 = $425. Choice A adds 20 percent to the sale price, which is the classic error because 20 percent of the smaller number is not the same amount as 20 percent of the larger one.",
  },

  // ---- Geometry and Trigonometry (3) ----
  {
    d: "geometry_trig",
    s: "area_volume",
    diff: "easy",
    type: "mc",
    prompt:
      "A rectangular tank measures 3 m by 4 m by 2 m. What is its volume, in cubic metres?",
    choices: ["9", "12", "24", "48"],
    ans: "C",
    exp: "Volume is the product of the three dimensions: 3 × 4 × 2 = 24 cubic metres. Choice B multiplies only the base dimensions, giving area rather than volume.",
  },
  {
    d: "geometry_trig",
    s: "right_triangles_trig",
    diff: "medium",
    type: "spr",
    prompt:
      "A right triangle has legs of length 9 and 12. What is the length of its hypotenuse?",
    ans: "15",
    alt: ["15.0"],
    exp: "By the Pythagorean theorem, 9² + 12² = 81 + 144 = 225, and √225 = 15. Answering 21 adds the legs instead of using their squares.",
  },
  {
    d: "geometry_trig",
    s: "circles",
    diff: "hard",
    type: "mc",
    prompt:
      "A central angle of 60° in a circle of radius 9 cuts off an arc. What is the length of that arc?",
    choices: ["3π", "6π", "9π", "18π"],
    ans: "A",
    exp: "A 60° angle is one sixth of the circle, and the circumference is 2π(9) = 18π, so the arc is 18π/6 = 3π. Choice B applies the fraction to the diameter-based value incorrectly by taking one third instead of one sixth.",
  },
];
